# Generated by Django 6.0.6 on 2026-06-23 16:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_a', models.CharField(help_text='Generic active ingredient A (lowercase)', max_length=200)),
                ('ingredient_b', models.CharField(help_text='Generic active ingredient B (lowercase)', max_length=200)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Moderate', max_length=20)),
                ('effect', models.TextField(help_text='Detailed description of the negative interaction')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_ingredient',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(default='BATCH-001', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='demand_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufactured_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='medicine',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='warehouse_location',
            field=models.CharField(default='Row A / Shelf 1', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, related_name='wishlist_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('frequency_days', models.PositiveIntegerField(default=30, help_text='Days between automatic deliveries (e.g. 30)')),
                ('next_delivery_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
