# Generated by Django 6.0.6 on 2026-06-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_druginteraction_medicine_active_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(default='tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
